@echo off
cd %~dp0\_Files
@echo disable "System Speaker"
devmanview /disable "System Speaker"
@echo disable "System Timer"
devmanview /disable "System Timer"
@echo disable "UMBus Root Bus Enumerator"
devmanview /disable "UMBus Root Bus Enumerator"
@echo disable Microsoft System Management BIOS Driver"
devmanview /disable "Microsoft System Management BIOS Driver"
@echo disable "High Precision Event Timer"
::devmanview /disable "Programmable Interrupt Controller" < https://media.discordapp.net/attachments/835904146413453333/931696968336551986/unknown.png
devmanview /disable "High Precision Event Timer"
@echo disable "PCI Encryption/Decryption Controller"
devmanview /disable "PCI Encryption/Decryption Controller"
@echo disable "AMD PSP"
devmanview /disable "AMD PSP"
@echo disable "Intel SMBus"
devmanview /disable "Intel SMBus"
@echo disable "Intel Management Engine"
devmanview /disable "Intel Management Engine"
@echo disable "PCI Memory Controller"
devmanview /disable "PCI Memory Controller"
@echo disable "PCI standard RAM Controller"
devmanview /disable "PCI standard RAM Controller"
@echo disable "Composite Bus Enumerator"
devmanview /disable "Composite Bus Enumerator"
@echo disable "Microsoft Kernel Debug Network Adapter"
devmanview /disable "Microsoft Kernel Debug Network Adapter"
@echo disable "SM Bus Controller"
devmanview /disable "SM Bus Controller"
@echo disable "NDIS Virtual Network Adapter Enumerator"
devmanview /disable "NDIS Virtual Network Adapter Enumerator"
@echo disable "Numeric Data Processor"
::devmanview /disable "Microsoft Virtual Drive Enumerator" < Breaks ISO mounts
devmanview /disable "Numeric Data Processor"
@echo disable "Microsoft RRAS Root Enumerator"
devmanview /disable "Microsoft RRAS Root Enumerator"
rem @echo disable "System Speaker"
pause