@echo off
cd %~dp0\_Files
@echo enable "System Speaker"
devmanview /enable "System Speaker"
@echo enable "System Timer"
devmanview /enable "System Timer"
@echo enable "UMBus Root Bus Enumerator"
devmanview /enable "UMBus Root Bus Enumerator"
@echo enable Microsoft System Management BIOS Driver"
devmanview /enable "Microsoft System Management BIOS Driver"
@echo enable "High Precision Event Timer"
::devmanview /enable "Programmable Interrupt Controller" < https://media.discordapp.net/attachments/835904146413453333/931696968336551986/unknown.png
devmanview /enable "High Precision Event Timer"
@echo enable "PCI Encryption/Decryption Controller"
devmanview /enable "PCI Encryption/Decryption Controller"
@echo enable "AMD PSP"
devmanview /enable "AMD PSP"
@echo enable "Intel SMBus"
devmanview /enable "Intel SMBus"
@echo enable "Intel Management Engine"
devmanview /enable "Intel Management Engine"
@echo enable "PCI Memory Controller"
devmanview /enable "PCI Memory Controller"
@echo enable "PCI standard RAM Controller"
devmanview /enable "PCI standard RAM Controller"
@echo enable "Composite Bus Enumerator"
devmanview /enable "Composite Bus Enumerator"
@echo enable "Microsoft Kernel Debug Network Adapter"
devmanview /enable "Microsoft Kernel Debug Network Adapter"
@echo enable "SM Bus Controller"
devmanview /enable "SM Bus Controller"
@echo enable "NDIS Virtual Network Adapter Enumerator"
devmanview /enable "NDIS Virtual Network Adapter Enumerator"
@echo enable "Numeric Data Processor"
::devmanview /enable "Microsoft Virtual Drive Enumerator" < Breaks ISO mounts
devmanview /enable "Numeric Data Processor"
@echo enable "Microsoft RRAS Root Enumerator"
devmanview /enable "Microsoft RRAS Root Enumerator"
rem @echo enable "System Speaker"
pause