@echo off
color C
mode 120,50


:1
echo 
echo.
echo. do u wanna clear your Obs Studio Cache file?
echo.
echo 1) Yes
echo 2) No
echo.
echo.

set /p menu=: 

if "%menu%"=="1" goto Language
if "%menu%"=="2" goto Exit

:Language
cls
cd C:\Program Files\obs-studio\data\obs-studio\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\coreaudio-encoder\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\enc-amf\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\frontend-tools\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\image-source\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\obs-ffmpeg\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\obs-filters
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\obs-outputs\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\obs-qsv11\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\obs-text\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\rtmp-services\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\text-freetype2\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\vlc-video\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\win-capture\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\win-decklink\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\win-dshow\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\win-wasapi\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\obs-browser\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini


cd C:\Program Files\obs-studio\data\obs-plugins\obs-transitions\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\obs-vst\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd C:\Program Files\obs-studio\data\obs-plugins\obs-x264\locale
del /s /q af-ZA.ini
del /s /q ar-SA.ini
del /s /q az-AZ.ini
del /s /q bg-BG.ini
del /s /q bn-BD.ini
del /s /q ca-ES.ini
del /s /q cs-CZ.ini
del /s /q da-dk.ini
del /s /q de-DE.ini
del /s /q el-GR.ini
del /s /q et-EE.ini
del /s /q eu-ES.ini
del /s /q fa-IR.ini
del /s /q fi-FI.ini
del /s /q fil-PH.ini
del /s /q fr-FR.ini
del /s /q gd-GB.ini
del /s /q gl-ES.ini
del /s /q he-IL.ini
del /s /q hi-IN.ini
del /s /q hr-HR.ini
del /s /q hu-HU.ini
del /s /q it-IT.ini
del /s /q ja-JP.ini
del /s /q ka-GE.ini
del /s /q ko-KR.ini
del /s /q ku-TR.ini
del /s /q It-LT.ini
del /s /q mn-MN.ini
del /s /q ms-MY.ini
del /s /q nb-NO.ini
del /s /q pa-IN.ini
del /s /q pl-PL.ini
del /s /q pt-BR.ini
del /s /q pt-PT.ini
del /s /q ro-RO.ini
del /s /q ru-RU.ini
del /s /q sk-SK.ini
del /s /q sl-SI.ini
del /s /q sq-AL.ini
del /s /q sr-CS.ini
del /s /q da-dk.ini
del /s /q lt-LT.ini
del /s /q nl-NL.ini
del /s /q nn-NO.ini
del /s /q sr-SP.ini
del /s /q sv-SE.ini
del /s /q ta-IN.ini
del /s /q th-TH.ini
del /s /q tl-PH.ini
del /s /q tr-TR.ini
del /s /q uk-UA.ini
del /s /q ur-PK.ini
del /s /q vi-vn.ini
del /s /q zh-cn.ini
del /s /q zh-tw.ini

cd "C:\Program Files\obs-studio\obs-plugins\64bit\locales"
del /s /q am.pak
del /s /q ar.pak
del /s /q bg.pak
del /s /q bn.pak
del /s /q ca.pak
del /s /q cs.pak
del /s /q da.pak
del /s /q de.pak
del /s /q el.pak
del /s /q en-GB.pak
del /s /q es.pak
del /s /q es-419.pak
del /s /q et.pak
del /s /q fa.pak
del /s /q fi.pak
del /s /q fil.pak
del /s /q fr.pak
del /s /q gu.pak
del /s /q he.pak
del /s /q hi.pak
del /s /q hr.pak
del /s /q hu.pak
del /s /q id.pak
del /s /q it.pak
del /s /q ja.pak
del /s /q kn.pak
del /s /q ko.pak
del /s /q it.pak
del /s /q lv.pak
del /s /q ml.pak
del /s /q mr.pak
del /s /q ms.pak
del /s /q ms.pak
del /s /q nb.pak
del /s /q nl.pak
del /s /q pl.pak
del /s /q pt-BR.pak
del /s /q pt-PT.pak
del /s /q ro.pak
del /s /q ru.pak
del /s /q sk.pak
del /s /q zh-TW.pak
del /s /q sl.pak
del /s /q sv.pak
del /s /q sw.pak
del /s /q ta.pak
del /s /q te.pak
del /s /q th.pak
del /s /q tr.pak
del /s /q uk.pak
del /s /q vi.pak
del /s /q zh-CN.pak
del /s /q lt.pak
del /s /q sr.pak
goto Themes

:Themes
cd C:\Program Files\obs-studio\data\obs-studio\themes
RMDIR /Q/S Acri
RMDIR /Q/S Rachni
del /s /q System.qss
del /s /q Acri.qss
del /s /q Rachni.qss
goto Others

:Others
cd C:\Users\%username%\AppData\Roaming\obs-studio
RMDIR /Q/S crashes
RMDIR /Q/S logs
RMDIR /Q/S updates
RMDIR /Q/S profiler_data

:Exit
Start https://www.instagram.com/dexxytb/
cls
Exit
