bcdedit /set useplatformclock No 
bcdedit /set allowedinmemorysettings 0
bcdedit /set useplatformtick Yes 
bcdedit /set tscsyncpolicy Legacy
bcdedit /set disabledynamictick Yes
bcdedit /set x2apicpolicy No
bcdedit /set perfmem 0
bcdedit /set uselegacyapicmode No 
bcdedit /set MSI Default
bcdedit /set debug No